@startuml
'see documentation at https://plantuml.com/sequence-diagram

title "MRI Scheduling"

actor Patient
actor Doctor #white
participant HMO
participant "Private insurer"
participant Provider

== Initial appointment==
Patient -> Doctor: goes for a consultation
Doctor -> Patient: gives referral\n//ServiceRequest//

== Appointment scheduling==
Patient -> Provider: check appointment dates (with 1..* providers), can email\n//Schedule+Slot//
Provider -> Patient: return possible dates (1..* dates), by phone, can take a few days\n//Schedule+Slot//
Patient -> Provider: request appointment\n//Appointment//
Provider -> Patient: confirm appointment\n//AppointmentResponse//

== Form 17==
Patient -> HMO: request form 17 using referral\n//Claim.use=preauthorization//
HMO -> Patient: filled form 17 with all details (such as procedure code)\n//ClaimResponse//

Group Alternative - private insurer
Patient -> "Private insurer": request form 17 using referral to a private insurer instead of HMO\n//Claim.use=preauthorization//
"Private insurer" -> Patient: filled form 17 with all details (such as procedure code)\n//ClaimResponse//
end

== Appointment cancellation (optional)==
Patient -> Provider: notify appointment cancellation\n//Appointment//
Provider -> Patient: confirm appointment cancellation\n//Appointment//

== Procedure report==
Patient -->> Provider: //get the procedure done//
Provider -> Doctor: send report (if provider and HMO are the same)\n//Procedure/DiagnosticReport//
Provider -> Patient: send report (if provider and HMO are different)\n//Procedure/DiagnosticReport//

@enduml
